config/routes.rb
Rails.application.routes.draw do

  resources :projects, only: [:index] do
    collection do
      post '/load_projects', to: 'projects#load_projects'
      get '/show_projects', to: 'projects#show_projects'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    has_one :tier

    attribute :name, :string
    attribute :description, :string
    attribute :stories, :string, array: true
    attribute :optionals, :string, array: true
    attribute :resources, :string, array: true
    attribute :examples, :string, array: true
end

app/models/tier.rb
class Tier < ApplicationRecord
    attribute :value, :integer
    attribute :description, :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    tier_list_request = ProjectConnector.new
    @response_code = tier_list_request.base_code

    if @response_code == 200
      @all_tiers = tier_list_request.base_response
      @counted_tiers = @all_tiers.count
      @stored_projects = Project.all.count
      @text_tiers = ''
      @all_tiers.each_with_index do |tier, index|
        @text_tiers += tier["name"]
        @text_tiers += " / " unless index == @all_tiers.length()-1
      end
    else
      @text_tiers = tier_list_request.base_message
    end
  end

  def load_projects
    found_tiers = params[:tiers] unless params[:tiers].blank?
    found_tiers.each do |tier|
      tier_value = tier["name"].split('-').first
      tier_name = tier["name"].split('-').last
      # save tier on model if doesn't exist in it.

      project_list_request = ProjectConnector.new(tier: tier["name"])
      all_projects = project_list_request.base_response
      all_projects.each do |project|
        project_request = ProjectConnector.new(tier: tier["name"], project: project["name"])
        puts("///////////#{project_request.project_details_response}")

        # save project on model if doesn't exist in it.
      end
    end
  end
  
  def show_projects; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title The Possimpible
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /
    meta charset="utf-8"
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"

  body.container
    .row
      .col-12.mt-2
        h2 Posible Projects
        = yield

app/views/projects/index.slim
- if @response_code == 200
  h4 #{@counted_tiers} tiers found in app-ideas repo.
  p = @text_tiers

  = form_with(url: load_projects_projects_path(tiers: @all_tiers), method: "post", data: { turbo: false }) do |f|
    .input-group.mb-3
      .input-group-prepend
        .input-group-text Load/Update Projects
      = f.submit 'Let\'s go!', class: 'btn btn-primary'
- else 
  h4 = @text_tiers
p.text-muted #{@stored_projects} projects loaded